In [1]:
# NUMPY STARTING

import numpy as np
a= np.array([1,2,3])
a

array([1, 2, 3])

#  Importance of using numpy over array(Based on memeory)

In [2]:
import sys
import numpy as np
l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


#  Numpy is more faster than List proof:

In [3]:
import time 
size = 10000000

l1= range(size)
l2= range(size)

a1 = np.arange(size)
a2 = np.arange(size)

# Python List
start= time.time()
result = [(x+y) for x, y in zip(l1, l2)]
print("Python list took:", (time.time()-start)*1000)

# Numpy List
start= time.time()
result = a1+a2
print("Numpy list took:", (time.time()-start)*1000)

Python list took: 962.4240398406982
Numpy list took: 122.67947196960449


# Properties for the Numpy Variable

In [4]:
# Different dimentional arrays

a= np.array([[1,2,3],[4,5,6]])
a[1][2]
a.shape

(2, 3)

In [5]:
a.ndim

2

In [6]:
a= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a.ndim
a[0][2]

array([7, 8, 9])

In [7]:
a.size


9

In [8]:
a.shape

(1, 3, 3)

In [9]:
a= np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype=complex)
a

array([[[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j],
        [7.+0.j, 8.+0.j, 9.+0.j]]])

In [10]:
# Array reshaping

a= np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype= float)
a.reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
a= np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype= int)
a.reshape(9,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [12]:
# To flatten n-dimentional arrays

a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Basic Mathematics functions:

a.min()

1

In [14]:
a.max()

9

In [15]:
a.sum()

45

In [16]:
# To find the sum of rows and columns of matrix:

a.sum(axis=1)

array([[12, 15, 18]])

In [17]:
a.sum(axis=2)

array([[ 6, 15, 24]])

# Properties for np array

In [18]:
np.ones((1,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
np.zeros((1,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
l =range(5)
l

range(0, 5)

In [21]:
l[4]

4

In [22]:
# Range Functions

np.arange(1,5)

array([1, 2, 3, 4])

In [23]:
np.arange(1,5,3)

array([1, 4])

In [24]:
# Line Spacing

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [26]:
a= np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype=int)
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
np.sqrt(a)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974],
        [2.64575131, 2.82842712, 3.        ]]])

In [28]:
np.std(a)

2.581988897471611

# Operations between two Numpy Arrays

In [29]:
a= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b= np.array([[[3,2,1],[6,5,4],[9,8,7]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
b

array([[[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [31]:
a+b

array([[[ 4,  4,  4],
        [10, 10, 10],
        [16, 16, 16]]])

In [32]:
a-b

array([[[-2,  0,  2],
        [-2,  0,  2],
        [-2,  0,  2]]])

In [33]:
a*b

array([[[ 3,  4,  3],
        [24, 25, 24],
        [63, 64, 63]]])

In [34]:
a/b

array([[[0.33333333, 1.        , 3.        ],
        [0.66666667, 1.        , 1.5       ],
        [0.77777778, 1.        , 1.28571429]]])

In [35]:
# Matrix Product

a.dot(b)

array([[[[ 42,  36,  30]],

        [[ 96,  81,  66]],

        [[150, 126, 102]]]])

In [36]:
import sys
sys.executable

'C:\\Users\\ASUS\\anaconda3\\envs\\pandas_env\\python.exe'

# Operations using nditer

In [37]:
import numpy as np
arr= np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
for rows in arr:
    print(rows)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [39]:
for rows in arr:
    for cell in rows:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [40]:
# To flatten numpy array into list

for cell in arr.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [41]:
for x in np.nditer(arr,order='c'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [42]:
for x in np.nditer(arr,order='f'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [43]:
# Prints values in matrix form in Fortran order 
ar=np.arange(12).reshape(3,4)
for x in np.nditer(ar, order='c',flags=['external_loop']):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
br = np.arange(3,15,4).reshape(3,1)
br

array([[ 3],
       [ 7],
       [11]])

In [47]:
for x,y in np.nditer([ar,br]):
    print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
